mobiledgex/edge-cloud-sampleapps

- android/MobiledgeXSDKDemo/app/build.gradle
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/MainActivity.java
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/qoe/QoeMapActivity.java
- android/MobiledgeXSDKDemo/app/src/main/res/values/strings.xml
- android/MobiledgeXSDKDemo/app/src/main/res/xml/pref_general.xml
- Fix error that occurred on first time changing DME preference because default value didn't include the port number too.
- Also catch exception when Directions API key isn't valid and display error Toast instead of crashing.
> Update default DME hostname

- unity/PongGameExample/PongServer/yawsps.js
The gameId as roomId concept already assumes 2 players. A disconnect from one, or both, or no players is enough to scrap the whole game, if any. Deleting roomId stops lingering game state for the current design. I bigger refactor is needed for proper N > 2 player support.
> Fixes a dead gameId by deleting upon disconnect (2 player only).

- unity/PongGameExample/PongGame/Assets/Scripts/GameManager.cs
- unity/PongGameExample/PongGame/Assets/Scripts/PlatformIntegration.cs
- unity/PongGameExample/PongGame/ProjectSettings/ProjectVersion.txt
Fixes Android PongGame threading related crash between GameManager async Task Start() and initialization of MobiledgeXIntegration object.
> Fix PongGame Android PlatformIntegration crash due to threading.

- unity/PingPongGameExample/PingPongGame/Assets/Scripts/GameManager.cs
- unity/PingPongGameExample/PingPongGame/Assets/Scripts/MobiledgeXIntegration.cs
- unity/PingPongGameExample/PingPongGame/Assets/Scripts/NetTest.cs
- unity/PingPongGameExample/PingPongGame/Assets/Scripts/PlatformIntegration.cs
- unity/PingPongGameExample/PingPongGame/ProjectSettings/ProjectSettings.asset
- Move IOS only symbols into ifdef. Fixes Android compile error with Unity IL2CPP scripting backend.
- NetTest now calculates average and stddev.
- Improve Exception handling on RegisterClient. Allow "App Not Found" to bubble up to outer handler.
> Update NetTest to record average and stddev, general fixes.

- FaceDetectionServer/Dockerfile_openpose
- FaceDetectionServer/Makefile
- FaceDetectionServer/moedx/tracker/apps.py
In order to support OpenPose in a Docker container, the "docker build" must take place on a machine with Nvidia drivers/libraries installed (i.e. not a MacBook). This update has the Makefile detect whether the Nvidia stuff is available by trying to execute the nvidia-smi command. If it is successful, a new version of the Dockerfile is used. Otherwise (like on a MacBook), the same old Dockerfile will be used.
> Docker OpenPose Integration

- android/MobiledgeXSDKDemo/app/build.gradle
- android/MobiledgeXSDKDemo/app/release/output.json
- android/MobiledgeXSDKDemo/app/src/main/AndroidManifest.xml
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/Cloudlet.java
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/CloudletDetailsActivity.java
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/CloudletListHolder.java
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/MainActivity.java
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/SpeedTestResultsInterface.java
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/qoe/QoeMapActivity.java
- android/MobiledgeXSDKDemo/app/src/main/res/layout/activity_cloudlet_details.xml
- android/MobiledgeXSDKDemo/app/src/main/res/values/strings.xml
- android/MobiledgeXSDKDemo/app/src/main/res/xml/pref_speed_test.xml
- android/MobiledgeXSDKDemo/build.gradle
- mobiledgexsdkdemo/getdata.go
- Added "UL SPEED TEST" to Cloudlet Details page.
- Removed dynamic/static download preference. Only dynamic will be used.
- New larger download preference values.
- Moved API key definition to local.properties, and added code to read them.
I meant to make the getdata.go code a separate PR, but it's only a single file, so I'm OK with it having slipped in here.
> Add upload speedtest

- unity/PingPongGameExample/PingPongGame/Assets/Scripts/GameManager.cs
- unity/PingPongGameExample/PingPongGame/Assets/Scripts/Integration/MobiledgeXIntegration.cs
- unity/PingPongGameExample/PingPongGame/Assets/Scripts/Integration/PlatformIntegration/NetInterfaceIntegration.cs
1) Removed useDemo which is the same as useWifiOnly
2) Replaced AndroidJNI code for NetInterface with Garner's SimpleNetInterface from c# sdk. Didn't realize we could pull that information directly with C# code. This fixes the weird crash we had when NetTest was running (probably some issue/ uncaught exception with the AndroidJNI code)
> Net interface update

- unity/PingPongGameExample/PingPongGame/Assets/Scripts/GameManager.cs
- unity/PingPongGameExample/PingPongGame/Assets/Scripts/Integration/MobiledgeXIntegration.cs
- unity/PingPongGameExample/PingPongGame/Assets/Scripts/Integration/PlatformIntegration/CarrierInfoIntegration.cs
- unity/PingPongGameExample/PingPongGame/Assets/Scripts/Integration/PlatformIntegration/PlatformIntegration.cs
- unity/PingPongGameExample/PingPongGame/Assets/Scripts/Integration/PlatformIntegration/PlatformIntegrationUtil.cs
- unity/PingPongGameExample/PingPongGame/Assets/Scripts/Integration/PlatformIntegration/UniqueIDIntegration.cs
- unity/PingPongGameExample/PingPongGame/Assets/Scripts/WsClient.cs
1) Had a bunch of functions for AndroidJNI calls with different return types (ie. call, callString, callInt). Just one generic function instead (ie. Call<int>)
2) Websocket client was creating a new MobiledgeXIntegration object instead of using the one that used throughout the rest of the app.
> Misc ping pong updates

- android/MobiledgeXSDKDemo/app/src/androidTest/java/com/mobiledgex/sdkdemo/MatchingEngineUnitTest.java
- createVerifyLocationRequest doesn't like tags=null. To avoid NPE, creating an empty list to use.
- A new exception caught.
> EDGECLOUD-188 - Updates for matchingengine 1.5

- FaceDetectionServer/client/multi_client.py
- FaceDetectionServer/moedx/tracker/apps.py
When apps.py is called by "manage.py makemigrations" or "manage.py migrate", abort initialization. This removes the warning in the bug that is referenced, but also cleans up a lot of extraneous output during the build and speeds up the build.
> EDGECLOUD-2435 - Do not perform app initialization for manage.py

- FaceDetectionServer/Makefile
The Jira bug says to clarify the error, but this update gets rid of the error by automatically updating the submodule whether the steps were done manually or not.
> EDGECLOUD-2446 - Auto update submodule

- FaceDetectionServer/client/multi_client.py
- FaceDetectionServer/moedx/tracker/apps.py
- FaceDetectionServer/moedx/tracker/consumers.py
- Previous fix exited too soon, and did not allow db initialization. This update doesn't import the detect/recognize classes in the case of manage.py db init calls.
- Cleanup for multi_client.py when show-responses is false.
> EDGECLOUD-2435 Do not exit. Allow db init.

- FaceDetectionServer/client/multi_client.py
- FaceDetectionServer/moedx/facial_detection/face_recognizer.py
- FaceDetectionServer/moedx/tracker/views.py
When I added websocket support, I switched from the Gunicorn web server to Uvicorn. This server supports async functions, and it also calls the class __init__ functions in async mode. Because Django database access is not allowed on an async thread, the code fails, and the training data download does not occur at startup.
The update will occur when face recognition is started, although there will be a delay in processing the first frame while the update happens. This won't affect latency stats though, because a 503/Unavailable is returned while the update is in progress.
I moved the initial training data download code out of __init__ and into its own function, then commented out the call so the "cannot call this from an async context" is no longer seen.
Note that all of this training data …
> EDGECLOUD-2447 Remove db access code from init function

- unity/PingPongGameExample/PingPongGame/Assets/Scripts/GameManager.cs
- unity/PingPongGameExample/PingPongGame/Assets/Scripts/Integration/MobiledgeXIntegration.cs
1) add IsEdgeEnabled check
- If GetConnectionProtocols is TCP or UDP, this will check if device HasCellular() and if the ip address bound to cellular interface exists. 
- If the GetConnectionProtocols is HTTP or Websockets, this will check if device HasCellular() and does not HasWifi(). This is because we do not have control of the local interface with these protocols, and they default to wifi if it is up. We also check to make sure the ip address bound to the cellular interface exists.
2) Throw exceptions from GetWebsocketConnection() if IsEdgeEnabled is false. Catch the exception in GameManager.cs (wsClient.Connect()) and useAltServer and call ConnectToServerWithRoomId() again if we cannot connect.
Exception: 
`Unable to get websocket connection. Exception: Device is not edge enabled. …
> EDGECLOUD-2575: Unity: IsEdgeAvailable()

- FaceDetectionServer/Dockerfile
- FaceDetectionServer/Dockerfile_openpose
- FaceDetectionServer/README.md
- FaceDetectionServer/client/multi_client.py
- FaceDetectionServer/moedx/tracker/apps.py
- FaceDetectionServer/moedx/tracker/utils.py
- FaceDetectionServer/moedx/tracker/views.py
- multi_client.py can use video for testing. 
- Frames are resized to the same dimensions as the Android demo app, unless overridden with --fullsize flag.
- --skip-frames parameter to send every Nth frame, for faster tests.
- Get weights file from faster server. Original location was a 10 minute DL every time you do a docker build.
- Moved CPU/GPU usage functions to utils.py so they they can be imported by other classes.
> EDGECLOUD-2618 Video and server usage support

- FaceDetectionServer/Dockerfile
- FaceDetectionServer/Dockerfile_openpose
An update to one of the Python dependencies caused the docker build to break. Changing the base image from python:3.6.6-onbuild to python:3.7.5 fixed the problem, but made the image file 4.23GB, up from 2.98GB. Using a multistage build to drop all of the stuff required for building from source resulted in a final image size of 2.61GB.
The GPU side was quite a bit trickier. I used the same basic technique: A first image that had everything needed to build libraries, including OpenPose, from source, and a second image that only included what is needed at runtime. I was not able to drop as many -dev libraries as I hoped, but I did get the final size down from 8.71GB to 6.3GB. Still way bigger that I would like, but the CUDA/CUDNN base is massive, OpenPose is huge, and the PyTorch stuff is …
> EDGECLOUD-2818 Docker multistage builds for smaller images

- FaceDetectionServer/Dockerfile_openpose
- FaceDetectionServer/requirements.txt
Install precompiled imagecodecs package. This allows us to get rid of the huge list of dependencies required to build from source.
> No longer build imagecodecs from source

- android/MobiledgeXSDKDemo/app/build.gradle
- android/MobiledgeXSDKDemo/app/release/output.json
- android/MobiledgeXSDKDemo/app/src/main/assets/about_dialog.html
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/MainActivity.java
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/MatchingEngineHelper.java
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/SettingsActivity.java
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/qoe/QoeMapActivity.java
- android/MobiledgeXSDKDemo/app/src/main/res/menu/activity_main_drawer.xml
- android/MobiledgeXSDKDemo/app/src/main/res/values/strings.xml
- android/MobiledgeXSDKDemo/app/src/main/res/xml/pref_general.xml
- android/MobiledgeXSDKDemo/app/src/main/res/xml/pref_matching_engine.xml
- android/MobiledgeXSDKDemo/app/src/main/res/xml/pref_speed_test.xml
- android/MobiledgeXSDKDemo/build.gradle
- android/MobiledgeXSDKDemo/computervision/build.gradle
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/EventItem.java
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ImageProcessorFragment.java
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ImageSender.java
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ImageServerInterface.java
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/MyEventRecyclerViewAdapter.java
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ObjectProcessorFragment.java
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/PoseProcessorFragment.java
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/SettingsActivity.java
- android/MobiledgeXSDKDemo/computervision/src/main/res/drawable/ic_baseline_more_24.xml
- android/MobiledgeXSDKDemo/computervision/src/main/res/layout/fragment_event.xml
- android/MobiledgeXSDKDemo/computervision/src/main/res/layout/fragment_event_list.xml
- android/MobiledgeXSDKDemo/computervision/src/main/res/layout/fragment_image_processor.xml
- android/MobiledgeXSDKDemo/computervision/src/main/res/menu/camera_menu.xml
- android/MobiledgeXSDKDemo/computervision/src/main/res/values/dimens.xml
- android/MobiledgeXSDKDemo/computervision/src/main/res/values/strings.xml
- android/MobiledgeXSDKDemo/computervision/src/main/res/xml/pref_face_detection.xml
This is the version I demoed at the Engineering meeting, plus Sunay's "Manual Failover" request, and correct WifiOnly handling.
More updates may be required as the app goes through QA, but hopefully they'll be minor.
- App name, version, organization can all be changed in General Settings.
- “About” dialog updated to show these values.
- HA: When Computer Vision server connectivity is lost, failover to next closest cloudlet.
- Added “Find Cloudlet” capabilities to Computer Vision activities.
- Added expandable log viewer to Computer Vision activities. Added expandable log viewer to Computer Vision activities. Long press to copy all contents to clipboard. If using Vysor or Scrcpy, it will also be copied to your desktop clipboard.
- New Setting to toggle display of public cloud processing …
> EDGECLOUD-2855 EDGECLOUD-2974 EDGECLOUD-3064 HA and more

- android/MobiledgeXSDKDemo/app/build.gradle
- android/MobiledgeXSDKDemo/app/release/output.json
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/MainActivity.java
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ImageProcessorFragment.java
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ImageSender.java
- android/MobiledgeXSDKDemo/computervision/src/main/res/values/strings.xml
Main concern here is to fix some NullPointerException crashes that had been submitted via Android's crash report tool. Some, I don't understand how they're possible to happen, but these updates will catch them and not crash.
> Fix NPE crashes, add long-press to clear log viewer.

- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/MainActivity.java
In version 59 of this client app, the backend app name changed from "MobiledgeX SDK Demo" to "ComputerVision". This method will update the General Settings custom app name Preference value accordingly.
However, we need to make sure this is only done once, in case the user specifically needs to connect to a "MobiledgeX SDK Demo" backend app and has updated their preferences manually. Because of this, we store a flag indicating that the upgrade has already happened so we can check the value and not perform it again.
> Upgrade app name in preferences only once.

- android/MobiledgeXSDKDemo/app/build.gradle
- android/MobiledgeXSDKDemo/app/src/androidTest/java/com/mobiledgex/sdkdemo/MatchingEngineUnitTest.java
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/MatchingEngineHelper.java
- android/MobiledgeXSDKDemo/app/src/main/res/values/strings.xml
- android/MobiledgeXSDKDemo/build.gradle
- android/MobiledgeXSDKDemo/computervision/build.gradle
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ImageProcessorFragment.java
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ImageSender.java
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ObjectProcessorFragment.java
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/PoseProcessorFragment.java
- android/MobiledgeXSDKDemo/computervision/src/main/res/layout/fragment_object_processor.xml
- android/MobiledgeXSDKDemo/computervision/src/main/res/layout/fragment_pose_processor.xml
- android/MobiledgeXSDKDemo/computervision/src/main/res/values/strings.xml
- android/WorkshopCompleted/.idea/codeStyles/Project.xml
- android/WorkshopCompleted/.idea/jarRepositories.xml
- android/WorkshopCompleted/app/build.gradle
- android/WorkshopCompleted/app/src/main/java/com/mobiledgex/workshopskeleton/FaceProcessorActivity.java
- android/WorkshopCompleted/app/src/main/java/com/mobiledgex/workshopskeleton/MainActivity.java
- android/WorkshopCompleted/app/src/main/res/layout/app_bar_main.xml
- android/WorkshopSkeleton/.idea/codeStyles/Project.xml
- android/WorkshopSkeleton/.idea/jarRepositories.xml
- android/WorkshopSkeleton/app/build.gradle
- android/WorkshopSkeleton/app/src/main/java/com/mobiledgex/workshopskeleton/MainActivity.java
- Change backend app name to ComputerVision.
- GPU CV activities will search for ComputerVision-GPU
- Added findCloudletGpu().
- Updated GPU-specific CV activities to include log viewer and HA testing menu items.
- Added testFindCloudletPerformance.
- App name updates for workshop apps.
> EDGECLOUD-3228 EDGECLOUD-3110 GPU-specific app instance support

- unity/PingPongGameExample/PingPongGame/Assets/Scripts/GameManager.cs
UseWifiOnly for Completed PingPong game. We want the initial introduction to MobiledgeX to be as seemless as possible. Once a developer decides to dig deeper in the.SkeletonApp, our docs we explain why UseWifiOnly is only for testing and there we ask them to send their mcc+mnc to be mapped in the backend
> EDGECLOUD-3162: Make Ping Pong Working Example have UseWifiOnly(true)

- iOS/ARShooterExample/ARShooterGame/ARShooter/LoginViewController/LoginViewController.swift
UseWifiOnly for DME API Calls. Set UseWifiOnly to false before GetWebsocketConnection (allow bind to cellular interface)
> EDGECLOUD-3162: ARShooter Completed Default to UseWifiOnly

- unity/PingPongGameExample/PingPongGame/Assets/Scripts/NetworkManager.cs
- unity/PingPongGameExample/PingPongGameSkeleton/Assets/Scripts/NetworkManager.cs
`-1` is not a valid value for `desired port` in the c# sdk anymore
> GetPortUpdate

- android/MobiledgeXSDKDemo/app/build.gradle
- android/MobiledgeXSDKDemo/app/release/output-metadata.json
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/MainActivity.java
- android/MobiledgeXSDKDemo/app/src/main/res/values/strings.xml
- android/MobiledgeXSDKDemo/build.gradle
- Instead of clearing the whole map and rebuilding all cloudlet and user location markers, use the existing cloudlet list (which contains a reference to its own marker) to reset icons, titles, and snippets as appropriate. 
- Track the user location marker in its own variable and update it as appropriate instead of recreating it each time.
> EDGECLOUD-3475 Rework icon coloring logic

- ComputerVisionServer/REST-API.md
- ComputerVisionServer/moedx/facial_detection/face_recognizer.py
- ComputerVisionServer/moedx/static/css/style.css
- ComputerVisionServer/moedx/static/js/index.js
- ComputerVisionServer/moedx/tracker/views.py
- CV server will start up even if Redis password is not defined, but training data will not be (cannot be) downloaded.
- /recognizer/predict/ calls will just do face detection and respond with a subject value of "No Training Password" so the client will be notified of a configuration error.
- Made 503 error body JSON so it could be parsed by the client.
> EDGECLOUD-3611 Allow server to start up even with missing Redis password

- android/MobiledgeXSDKDemo/app/build.gradle
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/Cloudlet.java
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/CloudletBuilder.java
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/MainActivity.java
- android/MobiledgeXSDKDemo/app/src/main/res/values/strings.xml
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ImageProcessorFragment.java
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ImageSender.java
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ObjectClassRenderer.java
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ObjectProcessorFragment.java
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/PoseProcessorFragment.java
- android/MobiledgeXSDKDemo/computervision/src/main/res/values/strings.xml
- android/MobiledgeXSDKDemo/computervision/src/main/res/xml/pref_face_detection.xml
- Builder support for Cloudlet class, standardized some member variable names.
- Custom hostname can be used for GPU CV activities if the override preference is enabled. 
- TLS support for speedtest and CV image sending, both https and wss.
- Bug fixes for GPU HA support.
> EDGECLOUD-3609 EDGECLOUD-3625 EDGECLOUD-3246 GPU hostname override, TLS support, orgName update

- android/MobiledgeXSDKDemo/README.md
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/CloudletDetailsActivity.java
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/MainActivity.java
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/SettingsActivity.java
- android/MobiledgeXSDKDemo/app/src/main/res/xml/pref_headers.xml
- android/MobiledgeXSDKDemo/computervision/src/androidTest/java/com/mobiledgex/computervision/ComputerVisionRestUnitTest.java
- android/MobiledgeXSDKDemo/computervision/src/main/assets/cvprovisioning.json
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ImageProcessorFragment.java
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ImageSender.java
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ObjectProcessorFragment.java
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/PoseProcessorFragment.java
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/PoseRenderer.java
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/SettingsActivity.java
- android/MobiledgeXSDKDemo/computervision/src/main/res/values/strings.xml
- android/MobiledgeXSDKDemo/computervision/src/main/res/xml/pref_face_detection.xml
- Provisioning data is downloaded from http://opencv.facetraining.mobiledgex.net/cvprovisioning.json.
- Removed usage of facedetection.defaultXXX.mobiledgex.net hostnames.
- Override settings to allow custom hostnames and ignore provisioning data.
- Better handling of TLS, disabling it for GCP app instances.
- Removed old preferences code from MainActivity that was replicated to computervision.ImageProcessorFragment and should have been removed long ago.
Testing still in progress, but I wanted folks to be able to start taking a look because this is a pretty sizable update.
> EDGECLOUD-3671 Use provisioning data instead of default hostnames

- ComputerVisionServer/Dockerfile_gpu
- ComputerVisionServer/moedx/client/remote_bench.py
- ComputerVisionServer/moedx/object_detection/object_detectron2.py
- Patch to comment Nvidia AMPERE support out of OpenPose to allow us to continue building with CUDA 10.
- Adding copyright to a file that are pointed to by soon-to-be-released blog post.
- Removed dead code and added TODO to object_detectron2.py.
> EDGECLOUD-4042 Patch OpenPose build to avoid error

- android/MobiledgeXSDKDemo/app/src/androidTest/java/com/mobiledgex/sdkdemo/MatchingEngineUnitTest.java
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/Cloudlet.java
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/CloudletDetailsActivity.java
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/CloudletListHolder.java
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/MatchingEngineHelper.java
- android/MobiledgeXSDKDemo/app/src/main/res/values/strings.xml
- android/MobiledgeXSDKDemo/build.gradle
- android/MobiledgeXSDKDemo/gradle/wrapper/gradle-wrapper.properties
- Removed hardcoded host and port numbers used for EdgeEvents demo with EdgeBox DME/app insts.
- Added "SDK NetTest" to "Latency Test Method" in Speed Test Settings.
- Code to use NetTest when it is selected.
> EDGECLOUD-4594 Removing hardcoded EdgeEvent host and adding NetTest option

- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/EdgeOnlyImageProcessorFragment.java
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ImageProcessorFragment.java
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ObjectProcessorFragment.java
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/PoseProcessorFragment.java
- android/MobiledgeXSDKDemo/computervision/src/main/res/values/strings.xml
- android/MobiledgeXSDKDemo/computervision/src/main/res/xml/pref_overrides.xml
Default was to always enable TLS, so we couldn't connect to a non-TLS server in the case of hostname override. New "TLS Enabled" switch setting that is only used when "Override Edge cloudlet hostname" is enabled.
When override is disabled, the TLS setting from the port section of the findCloudlet result is used.
> EDGECLOUD-5092 TLS Setting for override hostname

- android/WorkshopCompleted/.idea/compiler.xml
- android/WorkshopCompleted/.idea/misc.xml
- android/WorkshopCompleted/.idea/runConfigurations.xml
- android/WorkshopCompleted/app/build.gradle
- android/WorkshopCompleted/app/src/androidTest/java/com/mobiledgex/workshopskeleton/ExampleInstrumentedTest.java
- android/WorkshopCompleted/app/src/main/java/com/mobiledgex/workshopskeleton/FaceProcessorActivity.java
- android/WorkshopCompleted/app/src/main/java/com/mobiledgex/workshopskeleton/FaceProcessorFragment.java
- android/WorkshopCompleted/app/src/main/java/com/mobiledgex/workshopskeleton/MainActivity.java
- android/WorkshopCompleted/app/src/test/java/com/mobiledgex/workshopskeleton/ExampleUnitTest.java
- android/WorkshopCompleted/build.gradle
- android/WorkshopCompleted/gradle/wrapper/gradle-wrapper.properties
- android/WorkshopSkeleton/.idea/compiler.xml
- android/WorkshopSkeleton/.idea/misc.xml
- android/WorkshopSkeleton/.idea/runConfigurations.xml
- android/WorkshopSkeleton/app/build.gradle
- android/WorkshopSkeleton/app/src/androidTest/java/com/mobiledgex/workshopskeleton/ExampleInstrumentedTest.java
- android/WorkshopSkeleton/app/src/main/java/com/mobiledgex/workshopskeleton/FaceProcessorActivity.java
- android/WorkshopSkeleton/app/src/main/java/com/mobiledgex/workshopskeleton/FaceProcessorFragment.java
- android/WorkshopSkeleton/app/src/main/java/com/mobiledgex/workshopskeleton/MainActivity.java
- android/WorkshopSkeleton/app/src/main/res/layout/app_bar_main.xml
- android/WorkshopSkeleton/app/src/test/java/com/mobiledgex/workshopskeleton/ExampleUnitTest.java
- android/WorkshopSkeleton/build.gradle
- android/WorkshopSkeleton/gradle/wrapper/gradle-wrapper.properties
- Remove call to non-existent getPathPrefix
- Updated to matchingengine 2.4.2.
- Fixed bug where we were not including the setCarrierName call to build DME requests.
- Updated copyright dates.
- Library and plugin updates recommended by Android Studio
- Changes to sample unit test code required because of those updates.
> EDGECLOUD-4658 Workshop updates

- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/GpuImageProcessorFragment.java
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ImageProcessorFragment.java
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ImageSender.java
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ObjectProcessorFragment.java
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/PoseProcessorFragment.java
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/RollingAverage.java
- android/MobiledgeXSDKDemo/computervision/src/main/res/layout/fragment_image_processor.xml
- android/MobiledgeXSDKDemo/computervision/src/main/res/layout/fragment_object_processor.xml
- android/MobiledgeXSDKDemo/computervision/src/main/res/layout/fragment_pose_processor.xml
- android/MobiledgeXSDKDemo/computervision/src/main/res/values/strings.xml
- android/MobiledgeXSDKDemo/computervision/src/main/res/xml/pref_network.xml
- android/MobiledgeXSDKDemo/computervision/src/main/res/xml/pref_overrides.xml
- Renamed EdgeOnlyImageProcessorFragment to GpuImageProcessorFragment
- No more special preference for overriding GPU host. Edge host is used instead for the GPU activities.
- Got rid of useless conversions from nanoseconds to milliseconds and back again (*1000000, /1000000). Now we convert to ms when we add the measurement, and all other code expects ms values.
- Latency UI element labels now come from resource strings, and formatting is handled by resources.getString(). This allows us to specify a label format because while face detection has a "Full Process" heading and "Edge:" and "Cloud:" are where the values are actually displayed, the GPU activities have labels like "Full Process Latency:".
> Latency stats cleanup

- android/MobiledgeXSDKDemo/app/build.gradle
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/MainActivity.java
- android/MobiledgeXSDKDemo/build.gradle
- android/MobiledgeXSDKDemo/computervision/src/main/res/layout/fragment_pose_processor.xml
- android/MobiledgeXSDKDemo/matchingenginehelper/build.gradle
- android/MobiledgeXSDKDemo/matchingenginehelper/src/main/java/com/mobiledgex/matchingenginehelper/MatchingEngineHelper.java
- android/MobiledgeXSDKDemo/matchingenginehelper/src/main/java/com/mobiledgex/matchingenginehelper/SettingsActivity.java
- If AutoMigrate was set to true, any time the config was updated by preferences, the new config wasn't being used, because we weren't actually doing a startEdgeEvents(newConfig) to pass it in. Now we always to stop/start no matter the AutoMigrate setting.
- Fixed bug were changes on the "Edge Events Config" weren't setting the flag that we need to restart with a new config (`MatchingEngineHelper.mEdgeEventsConfigUpdated = true;`)
- Got rid of newConnection parameter, since we restart no matter whether the connection is new or not.
> AutoMigrate rework.

- android/MobiledgeXSDKDemo/app/build.gradle
- android/MobiledgeXSDKDemo/app/src/main/assets/about_dialog.html
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/MainActivity.java
- android/MobiledgeXSDKDemo/app/src/main/res/xml/pref_route_mode.xml
- android/MobiledgeXSDKDemo/build.gradle
- android/MobiledgeXSDKDemo/matchingenginehelper/src/main/java/com/mobiledgex/matchingenginehelper/MatchingEngineHelper.java
- android/MobiledgeXSDKDemo/matchingenginehelper/src/main/res/values/strings.xml
- android/MobiledgeXSDKDemo/matchingenginehelper/src/main/res/xml/pref_matching_engine.xml
- Added "Use Wifi Only" setting. If value is false, carrierName comes from prefs. If true, carrierName comes from me.getCarrierName(), which currently is "" for the wifi-only case.
- Remove hard-coded 8008 from Cloudlet.java latency test code, and EVENT_LATENCY_REQUEST handling code. Use port info returned by the DME.
- Added CSS to "About" HTML to the use MobiledgeX colors instead of stark black and white.
- To add a waypoint, after driving route created, long-press on map, and select "Add waypoint to route".
- Individual waypoints can be dragged and dropped just like the start and end markers.
- New defaults/max values for animation times.
- Bug fixes when switching between driving and flying route modes.
> Adding waypoint support for Driving Route mode

- android/MobiledgeXSDKDemo/README.md
- android/MobiledgeXSDKDemo/app/build.gradle
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/Cloudlet.java
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/MainActivity.java
- android/MobiledgeXSDKDemo/app/src/main/res/values/strings.xml
- android/MobiledgeXSDKDemo/app/src/main/res/xml/pref_route_mode.xml
- android/MobiledgeXSDKDemo/build.gradle
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/Camera2BasicFragment.java
- android/MobiledgeXSDKDemo/matchingenginehelper/src/main/java/com/mobiledgex/matchingenginehelper/EventLogViewer.java
- android/MobiledgeXSDKDemo/matchingenginehelper/src/main/java/com/mobiledgex/matchingenginehelper/MatchingEngineHelper.java
- Reduce the number of points used to draw the driving route. Processing too many points during animation was bogging down older phones. Added new "Reduction" preference to allow fine tuning.
- Fix crash when turning off route mode during playback.
- When new cloudlet is introduced via FindCloudletEvent, draw it in green to show it is closest.
- When cloudlet is removed, mark it as such, so we can change the info window shippet to "Has been removed".
- Hide "Verify Location" menu item as we don't currently want to expose that API call.
- Enable desugaring to support java.time.LocalDateTime from Java 8 on API < 26.
> EDGECLOUD-5537 EDGECLOUD-5563 EDGECLOUD-5414

- android/MobiledgeXSDKDemo/CHANGELOG.md
- android/MobiledgeXSDKDemo/app/build.gradle
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/MainActivity.java
- android/MobiledgeXSDKDemo/app/src/main/res/xml/pref_speed_test.xml
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ImageProcessorFragment.java
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ObjectProcessorFragment.java
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/PoseProcessorFragment.java
- android/MobiledgeXSDKDemo/matchingenginehelper/src/main/java/com/mobiledgex/matchingenginehelper/MatchingEngineHelper.java
- android/MobiledgeXSDKDemo/matchingenginehelper/src/main/res/xml/pref_general.xml
- android/WorkshopCompleted/.idea/misc.xml
- android/WorkshopCompleted/app/build.gradle
- android/WorkshopCompleted/app/src/main/java/com/mobiledgex/workshopskeleton/MainActivity.java
- android/WorkshopCompleted/app/src/main/res/layout/content_main.xml
- android/WorkshopCompleted/build.gradle
- Remove verifyLocation completely from Workshop app.
- Hide "Verify Location" menu item, and skip verifyLocation when pressing the lower-right "Do all steps" button. This can easily be added back by changing the VERIFY_LOCATION_ENABLED constant value.
- Updated CHANGLOG.
- Fixed pause not working during route mode.
- Instead of performing getAppInstList() every time any applicable setting is changed, now we only do it when resuming the MainActivity after exiting the SettingsActivity. Any applicable setting updates the static variable mAppDefinitionUpdated and that is checked in onResume().
- Pose and Object detection were not correctly handling hostname override settings. Fixed.
- Fixed TLS selection when starting CV activities. Now works properly for TLS and non-TLS.
- Fixed bug where …
> EDGECLOUD-5414 Removing verifyLocation, using working default settings

- android/MobiledgeXSDKDemo/app/build.gradle
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/MainActivity.java
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/qoe/QoeMapActivity.java
- android/MobiledgeXSDKDemo/build.gradle
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ImageProcessorFragment.java
- android/MobiledgeXSDKDemo/matchingenginehelper/src/main/java/com/mobiledgex/matchingenginehelper/MatchingEngineHelper.java
- android/MobiledgeXSDKDemo/matchingenginehelper/src/main/java/com/mobiledgex/matchingenginehelper/MatchingEngineHelperInterface.java
- Remove subscription to handleLatencyRequest. Let the SDK handle it.
- Better tracking of the flags mEdgeEventsConfigUpdated and mAppDefinitionUpdated, to be checked in onResume.
- Add "background" parameter to getCloudlets, so if onResume needs to call it, it will be in the background and not pause the UI when you close the Settings page.
> EDGECLOUD-5603 EDGECLOUD-5592

- android/WorkshopCompleted/app/build.gradle
- android/WorkshopCompleted/app/src/main/java/com/mobiledgex/workshopskeleton/FaceProcessorFragment.java
- android/WorkshopCompleted/app/src/main/java/com/mobiledgex/workshopskeleton/MainActivity.java
- android/WorkshopCompleted/build.gradle
- Instead of a Snackbar, display errors in the Event Log Viewer.
- Remove duplicate error messages.
- Overriding the value of generateDmeHostAddress() with always-working EU DME. Code comment about why this is done.
> Move errors to Event Log Viewer, remove duplicates

- android/MobiledgeXSDKDemo/CHANGELOG.md
- android/MobiledgeXSDKDemo/app/build.gradle
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/MainActivity.java
- android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ImageProcessorFragment.java
- android/MobiledgeXSDKDemo/matchingenginehelper/src/main/java/com/mobiledgex/matchingenginehelper/SettingsActivity.java
- android/MobiledgeXSDKDemo/matchingenginehelper/src/main/res/values/strings.xml
- android/MobiledgeXSDKDemo/matchingenginehelper/src/main/res/xml/pref_matching_engine.xml
- Use correct video file name for Object Detection activity. (Was being incorrectly overridden in parent class's startImageSenders() method.)
- To allow for higher values, change "Get App Inst Limit" Setting to use a numeric-only text input field.
- Added a SummaryProvider for the setting.
> EDGECLOUD-5672 EDGECLOUD-5677 Vid name and app inst limit update

- android/MobiledgeXSDKDemo/app/build.gradle
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/DtQosPrioritySessions.java
- android/MobiledgeXSDKDemo/build.gradle
- android/MobiledgeXSDKDemo/computervision/build.gradle
- android/MobiledgeXSDKDemo/matchingenginehelper/build.gradle
- android/MobiledgeXSDKDemo/matchingenginehelper/src/main/java/com/mobiledgex/matchingenginehelper/MatchingEngineHelper.java
- Removed direct calls to DT's REST API server.
- "Update QOS Session" dialog now calls SDK's QosPrioritySession create/delete methods via MatchingEngineHelper.java.
- Removed getLocalIp methods and now call SDK's public methods.
- Removed MEL vestiges.
> EDGECLOUD-6088 Demo app - Add support for QosPrioritySession APIs

- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/DtQosPrioritySessions.java
- android/MobiledgeXSDKDemo/build.gradle
- android/MobiledgeXSDKDemo/matchingenginehelper/src/main/java/com/mobiledgex/matchingenginehelper/MatchingEngineHelper.java
- If FindCloudlet hadn't been performed, and a QOS profile is chosen from the "Update Session Priority" dialog, the session creation attempt would fail, because things like the app inst FQDN were not available, but there was no indication to the user of the failure. This update checks for all required values before session creation attempt, and shows an error appropriately.
- Also fixed a crash on "app not found" that was caused by not catching io.grpc.StatusRuntimeException everywhere it was needed.
- Fix for not keeping "UNRECOGNIZED" out of the profile name list because enum value wasn't compared correctly.
- Update SDK to 3.0.10
> EDGECLOUD-6182 Fix 'Update QOS Session' silent failure

- ComputerVisionServer/Dockerfile
- ComputerVisionServer/Dockerfile_gpu
- ComputerVisionServer/moedx/client/multi_client.py
- ComputerVisionServer/moedx/tracker/apps.py
- ComputerVisionServer/moedx/tracker/routing.py
- ComputerVisionServer/moedx/tracker/views.py
- ComputerVisionServer/requirements.txt
- Remove server code (leaving moedx/facial_detection/tcp_server.py for reference).
- Remove test script code.
- Removing version restrictions on a couple of Python libraries. Minor routing.py code fix to support newer version of "channels".
> EDGECLOUD-6183 Remove Persistent TCP Server support

- android/MobiledgeXSDKDemo/app/src/main/AndroidManifest.xml
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/Cloudlet.java
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/CloudletBuilder.java
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/CloudletDetailsActivity.java
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/MainActivity.java
- android/MobiledgeXSDKDemo/build.gradle
- android/MobiledgeXSDKDemo/computervision/build.gradle
- android/MobiledgeXSDKDemo/matchingenginehelper/src/main/java/com/mobiledgex/matchingenginehelper/MatchingEngineHelper.java
- Pass in Context when initializing a Cloudlet so it can be used in the background for NetTest on auto start latency test.
- For driving route animation, make pause button actually pause the animation. (How did this never work before?)
- Fix first-run default for mMatchingEngineSSL boolean.
- Upgraded API versions based on Android Studio's recommendation. This caused some bugs:
- routeBetweenPoints() has a mix of networking calls and UI update calls. Everything was working fine, but API 30 caused some "java.lang.IllegalStateException: Not on the main thread" and CalledFromWrongThreadExceptions to be thrown. Needed to rework the method to run in the background and update the UI via runOnUiThread().
- Upgraded okhttp3 lib version due to NoSuchMethodException introduced in older versions by …
> EDGECLOUD-6238, EDGECLOUD-6255. NetTest and Route Mode  bug fixes

- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/MainActivity.java
- android/MobiledgeXSDKDemo/matchingenginehelper/src/main/java/com/mobiledgex/matchingenginehelper/MatchingEngineHelper.java
- android/MobiledgeXSDKDemo/matchingenginehelper/src/main/java/com/mobiledgex/matchingenginehelper/SettingsActivity.java
- When wifi-only is turned on, editing of the Operator preferences is disabled.
- When wifi-only is turned on, always use "" (wildcard) value for setCarrierName() for any MatchingEngine call.
> EDGECLOUD-6331 Carrier name fix for wifi-only

- android/MobiledgeXSDKDemo/THIRD_PARTY_LICENSES.txt
- android/MobiledgeXSDKDemo/app/build.gradle
- android/MobiledgeXSDKDemo/app/release/output-metadata.json
- android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/MainActivity.java
- android/MobiledgeXSDKDemo/app/src/main/res/drawable/ic_menu_licenses.xml
- android/MobiledgeXSDKDemo/app/src/main/res/menu/activity_main_drawer.xml
- android/MobiledgeXSDKDemo/app/src/main/res/values/strings.xml
- android/MobiledgeXSDKDemo/build.gradle
- android/MobiledgeXSDKDemo/gradle/wrapper/gradle-wrapper.properties
- Added 'Open source notices' menu item which launches OssLicensesMenuActivity to display licenses.
- Added generateThirdPartyLicensesTxt Gradle task to generate a flat text file of the same. Thanks, @lgarner!
> Add 'Open source notices' menu item to display licenses. Text file of same.
