unity/PongGameExample/PongGame/Assets/Scripts/MobiledgeXIntegration.cs

RegisterClient Debug message fix.

---

unity/PongGameExample/PongGame/Assets/Scripts/GameManager.cs
unity/PongGameExample/PongGame/Assets/Scripts/MobiledgeXIntegration.cs
unity/PongGameExample/PongGameSkeleton/Assets/Scripts/GameManager.cs
unity/PongGameExample/PongGameSkeleton/Assets/Scripts/MobiledgeXIntegration.cs

Catch DmeDnsException on outer most try to allow failover to public cloud.

---

FaceDetectionServer/moedx/facial_detection/faceRecognizer.py
FaceDetectionServer/moedx/tracker/apps.py

Adds a timeout to the requests sent to FaceTrainingServer. This means if the server can't be reached, the request will return before the worker thread times out and gets killed, and the startup procedure can continue.
Also updates for EDGECLOUD-1349. Environment variables can be used to override ports:
- FD_TRAINING_DATA_PORT, default is 8009
- FD_PERSISTENT_TCP_PORT, default is 8011

EDGECLOUD-1351 Fix restart loop

---

android/MobiledgeXSDKDemo/README.md

Edited for grammar.

---

unity/PingPongGameExample/PingPongGame/Assets/Scripts/GameManager.cs
unity/PingPongGameExample/PingPongGame/Assets/Scripts/MobiledgeXIntegration.cs
unity/PingPongGameExample/PingPongGame/Assets/Scripts/PlatformIntegration.cs

EDGECLOUD-1763 pingpong csharp Use MCCMNC for carrierName. Fix return values.

---

android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/MainActivity.java
android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/TrainGuestDialog.java

No more special, simplified logic for the default environment.

EDGECLOUD-1840 - Standardize verifyLocation results

---

FaceDetectionServer/Makefile
FaceDetectionServer/client/server_tester.py
FaceDetectionServer/moedx/moedx/settings.py
FaceDetectionServer/moedx/moedx/urls.py
FaceDetectionServer/moedx/tracker/apps.py
FaceDetectionServer/moedx/tracker/views.py

- New image name in Makefile
- Added /getdata and /uploaddata endpoints to FaceDetectionServer
- Fixed bug in image built with GPU support, and executed on a non-GPU machine.

EDGECLOUD-1873 - Combined backend for SDK demo app

---

unity/PingPongGameExample/PingPongGame/Assets/Scripts/GameManager.cs
unity/PingPongGameExample/PingPongGame/Assets/Scripts/LocationService.cs
unity/PingPongGameExample/PingPongGame/Assets/Scripts/MobiledgeXIntegration.cs
unity/PingPongGameExample/PingPongGame/Assets/Scripts/PlatformIntegration.cs

Mini fix, and misc pointing to new instance of PingPong server.

Remove runTest = true, fix net test in Unity.

---

unity/PingPongGameExample/PingPongGame/Assets/Scripts/GameManager.cs
unity/PingPongGameExample/PingPongGame/Assets/Scripts/Integration/MobiledgeXIntegration.cs
unity/PingPongGameExample/PingPongGame/Assets/Scripts/Integration/PlatformIntegration/CarrierInfoIntegration.cs
unity/PingPongGameExample/PingPongGame/Assets/Scripts/Integration/PlatformIntegration/PlatformIntegration.cs
unity/PingPongGameExample/PingPongGame/Assets/Scripts/Integration/PlatformIntegration/PlatformIntegrationUtil.cs
unity/PingPongGameExample/PingPongGame/Assets/Scripts/Integration/PlatformIntegration/UniqueIDIntegration.cs
unity/PingPongGameExample/PingPongGame/Assets/Scripts/WsClient.cs

* use generics instead of bunch of androidjni functions
* fix websocket client (use same integration object for app continuity)

Misc ping pong updates (#153)

---

unity/PingPongGameExample/PingPongGame/ProjectSettings/ProjectSettings.asset
unity/PingPongGameExample/PingPongGameSkeleton/Assets/Scripts/GameManager.cs
unity/PingPongGameExample/PingPongGameSkeleton/Assets/Scripts/Integration/MobiledgeXIntegration.cs
unity/PingPongGameExample/PingPongGameSkeleton/Assets/Scripts/Integration/PlatformIntegration/CarrierInfoIntegration.cs
unity/PingPongGameExample/PingPongGameSkeleton/Assets/Scripts/Integration/PlatformIntegration/NetInterfaceIntegration.cs
unity/PingPongGameExample/PingPongGameSkeleton/Assets/Scripts/Integration/PlatformIntegration/PlatformIntegration.cs
unity/PingPongGameExample/PingPongGameSkeleton/Assets/Scripts/Integration/PlatformIntegration/UniqueIDIntegration.cs
unity/PingPongGameExample/PingPongGameSkeleton/Assets/Scripts/WsClient.cs
unity/PingPongGameExample/PingPongGameSkeleton/ProjectSettings/ProjectVersion.txt

Should be the same changes I made to PingPongGame to fix the android crash and update NetInterface.
Will update doc once approved

update pingpongskeleton, fix android crash

---

android/MobiledgeXSDKDemo/app/build.gradle
android/MobiledgeXSDKDemo/app/release/output.json
android/MobiledgeXSDKDemo/app/src/main/AndroidManifest.xml
android/MobiledgeXSDKDemo/app/src/main/assets/about_dialog.html
android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/MainActivity.java
android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/qoe/QoeMapActivity.java
android/MobiledgeXSDKDemo/app/src/main/res/menu/activity_main_drawer.xml
android/MobiledgeXSDKDemo/app/src/main/res/values/strings.xml
android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ImageProcessorFragment.java
android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ImageSender.java
android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ObjectClassRenderer.java
android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ObjectProcessorActivity.java
android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ObjectProcessorFragment.java
android/MobiledgeXSDKDemo/computervision/src/main/res/layout/fragment_object_processor.xml
android/MobiledgeXSDKDemo/computervision/src/main/res/values/strings.xml

This is the client side update to support an Object Detection activity.
Also:
- EDGECLOUD-2261 Demo app - Add backend info to "About" dialog
- EDGECLOUD-157 Demo app "About" dialog/page with links

EDGECLOUD-2001 Add object detection using GPU-accelerated library

---

iOS/ARShooterExample/ARShooterGame/ARShooter/Info.plist
iOS/ARShooterExample/ARShooterGame/ARShooter/LoginViewController/LoginViewController.swift
iOS/ARShooterExample/ARShooterGame/Podfile
iOS/ARShooterExample/ARShooterGame/Podfile.lock
iOS/ARShooterExample/ARShooterSkeleton/ARShooterSkeleton/LoginViewController/LoginViewController.swift
iOS/ARShooterExample/ARShooterSkeleton/Podfile
iOS/ARShooterExample/ARShooterSkeleton/Podfile.lock

Swift MatchingEngine update to 1.5:
1) devName -> orgName
2) Codable objects instead of dictionaries for API requests and replies

EDGECLOUD-2306: IOS swift app changes for DME api needs to change dev_name to operator_name

---

android/MobiledgeXSDKDemo/app/build.gradle
android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/MatchingEngineHelper.java
android/MobiledgeXSDKDemo/build.gradle
android/WorkshopCompleted/app/build.gradle
android/WorkshopCompleted/app/src/main/java/com/mobiledgex/workshopskeleton/MainActivity.java
android/WorkshopSkeleton/app/build.gradle
android/WorkshopSkeleton/app/src/main/java/com/mobiledgex/workshopskeleton/MainActivity.java

Changes for demo app and workshop apps.

EDGECLOUD-2242 devName to orgName

---

android/MobiledgeXSDKDemo/app/build.gradle
android/MobiledgeXSDKDemo/app/release/output.json
android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/Cloudlet.java
android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/CloudletDetailsActivity.java
android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/MainActivity.java
android/MobiledgeXSDKDemo/build.gradle
android/MobiledgeXSDKDemo/computervision/build.gradle
android/MobiledgeXSDKDemo/computervision/src/androidTest/java/com/mobiledgex/computervision/ComputerVisionRestUnitTest.java
android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ImageProcessorFragment.java
android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ImageSender.java
android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ObjectProcessorFragment.java
android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/PoseProcessorFragment.java
android/MobiledgeXSDKDemo/computervision/src/main/res/values/strings.xml
android/MobiledgeXSDKDemo/gradle/wrapper/gradle-wrapper.properties

- Websocket client using okhttp3.WebSocket.
- ImageSender now uses builder instead of old, unwieldy constructor.
- Added date and time to stats output.
- Cloudlet Details updates for displaying latency test method, and whether socket method is forced because the server doesn't support it (Azure), or we are running on an emulator.

Websocket support

---

iOS/ARShooterExample/ARShooterGame/ARShooter/LoginViewController/LoginViewController.swift
iOS/ARShooterExample/ARShooterServer/Dockerfile
iOS/ARShooterExample/ARShooterServer/shooter-server.js
iOS/ARShooterExample/ARShooterSkeleton/ARShooterSkeleton/LoginViewController/LoginViewController.swift

Hopefully this port doesn't have any hidden meanings
After redeploying, also changed the orgName to MobiledgeX

Arshooter new port

---

android/WorkshopCompleted/.idea/gradle.xml
android/WorkshopCompleted/app/build.gradle
android/WorkshopCompleted/app/src/main/java/com/mobiledgex/workshopskeleton/FaceProcessorActivity.java
android/WorkshopCompleted/app/src/main/java/com/mobiledgex/workshopskeleton/FaceProcessorFragment.java
android/WorkshopCompleted/app/src/main/java/com/mobiledgex/workshopskeleton/MainActivity.java
android/WorkshopCompleted/app/src/main/res/layout/activity_main.xml
android/WorkshopCompleted/app/src/main/res/layout/app_bar_main.xml
android/WorkshopCompleted/app/src/main/res/layout/content_main.xml
android/WorkshopCompleted/app/src/main/res/layout/fragment_face_processor.xml
android/WorkshopCompleted/build.gradle
android/WorkshopCompleted/gradle.properties
android/WorkshopCompleted/gradle/wrapper/gradle-wrapper.properties
android/WorkshopSkeleton/.idea/gradle.xml
android/WorkshopSkeleton/app/build.gradle
android/WorkshopSkeleton/app/src/main/java/com/mobiledgex/workshopskeleton/FaceProcessorActivity.java
android/WorkshopSkeleton/app/src/main/java/com/mobiledgex/workshopskeleton/FaceProcessorFragment.java
android/WorkshopSkeleton/app/src/main/java/com/mobiledgex/workshopskeleton/MainActivity.java
android/WorkshopSkeleton/app/src/main/res/layout/activity_main.xml
android/WorkshopSkeleton/app/src/main/res/layout/app_bar_main.xml
android/WorkshopSkeleton/app/src/main/res/layout/content_main.xml
android/WorkshopSkeleton/app/src/main/res/layout/fragment_face_processor.xml
android/WorkshopSkeleton/gradle.properties

1) Migrate WorkshopCompleted and WorkshopSkeleton to androidx
2) devName -> orgName
3) Bump to 2.0
4) createDefault[]Request with fewer params
5) Add GetConnection workflow base code to WorkshopSkeleton
6) Separate FindCloudlet and RegisterClient:
- FindCloudlet has its own Background request object that updates UI elements after completion (after returning to UI thread)
- make sure other API background requests update UI elements after completion
Doc changes here: https://github.com/mobiledgex/devcenter/pull/9

EDGECLOUD-2501: Update Android Workshop with Orgname changes

---

unity/PingPongGameExample/PingPongGame/Assets/Scripts/Integration/MobiledgeXIntegration.cs
unity/PingPongGameExample/PingPongGameSkeleton/Assets/Scripts/GameManager.cs
unity/PingPongGameExample/PingPongGameSkeleton/Assets/Scripts/Integration/MobiledgeXIntegration.cs

Doc changes here: https://github.com/mobiledgex/devcenter/pull/8
1) Update Create[]Request parameters for PingPongGame
2) Add IsEdgeAvailable() code to PingPongSkeleton

EDGECLOUD-2500: Update Unity Workshop with Orgname changes

---

unity/PingPongGameExample/PingPongGame/Assets/Scripts/Integration/MobiledgeXIntegration.cs

Redeployed PongGamed -> updated appVers and carrierName

update ponggame dme params

---

iOS/ARShooterExample/ARShooterGame/ARShooter/LoginViewController/LoginViewController.swift
iOS/ARShooterExample/ARShooterGame/Podfile
iOS/ARShooterExample/ARShooterGame/Podfile.lock
iOS/ARShooterExample/ARShooterSkeleton/ARShooterSkeleton/LoginViewController/LoginViewController.swift
iOS/ARShooterExample/ARShooterSkeleton/Podfile

Updating iOS Sample app
1. Removing excess args from ARShooter (Completed Version).
2. Updating Podfile for ARShooterSkeleton and ARShooterCompleted.
3. Adding Errors enum to ARShooterSkeleton.
4. Removing matchingEngine var from ARShooterSkeleton to match with the documentation.

Updating CompletedARShooter

---

android/SDKValidator/app/build.gradle
android/SDKValidator/app/src/androidTest/java/com/mobiledgex/sdkvalidator/EngineCallTest.java
android/SDKValidator/app/src/androidTest/java/com/mobiledgex/sdkvalidator/FindCloudletTest.java
android/SDKValidator/app/src/androidTest/java/com/mobiledgex/sdkvalidator/RegisterClientTest.java
android/SDKValidator/app/src/main/java/com/mobiledgex/sdkvalidator/MainActivity.java

Tested on Samsung Galaxy S8 with SIM pulled.

EDGECLOUD-2816 Handle case of retrieveCellId returning null

---

FaceDetectionServer/REST-API.md

Fixing a couple of mistakes found during review.

EDGECLOUD-2923 Fixing typos.

---

android/MobiledgeXSDKDemo/app/build.gradle
android/MobiledgeXSDKDemo/app/src/androidTest/java/com/mobiledgex/sdkdemo/MatchingEngineUnitTest.java
android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/MatchingEngineHelper.java
android/MobiledgeXSDKDemo/build.gradle
android/MobiledgeXSDKDemo/computervision/src/androidTest/java/com/mobiledgex/computervision/ComputerVisionRestUnitTest.java

Updating to SDK version 2.0.8 and MEL 1.0.8. Temporarily pulling from maven-development.

EDGECLOUD-2929 MEL support. Also a little AndroidX cleanup.

---

android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/SettingsActivity.java
android/MobiledgeXSDKDemo/build.gradle
android/MobiledgeXSDKDemo/computervision/build.gradle
android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/Camera2BasicFragment.java
android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/FaceBoxRenderer.java
android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ImageProcessorFragment.java
android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ImageSender.java
android/MobiledgeXSDKDemo/computervision/src/main/res/layout/fragment_image_processor.xml
android/MobiledgeXSDKDemo/computervision/src/main/res/layout/fragment_object_processor.xml
android/MobiledgeXSDKDemo/computervision/src/main/res/layout/fragment_pose_processor.xml
android/SDKValidator/.idea/jarRepositories.xml

Client side changes ended up being minimal. This update also includes some cleanup from the AndroidX migration and logs quietening.

EDGECLOUD-2684 Training data stored in Redis

---

iOS/ARShooterExample/ARShooterGame/ARShooter/LoginViewController/LoginViewController.swift
iOS/ARShooterExample/ARShooterGame/Podfile
iOS/ARShooterExample/ARShooterGame/Podfile.lock
iOS/ARShooterExample/ARShooterSkeleton/ARShooterSkeleton/LoginViewController/LoginViewController.swift
iOS/ARShooterExample/ARShooterSkeleton/Podfile
iOS/ARShooterExample/ARShooterSkeleton/Podfile.lock

Docs PR: https://github.com/mobiledgex/devcenter/pull/73
1. 2.1.0 updates
2. Non-demo mode was crashing, because I tried to grab location before having proper permissions

Update ARShooter with 2.1.0 SDK

---

android/MobiledgeXSDKDemo/app/release/output.json
android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/MainActivity.java
android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/MatchingEngineHelper.java
android/MobiledgeXSDKDemo/app/src/main/res/values/strings.xml
android/MobiledgeXSDKDemo/app/src/main/res/xml/pref_matching_engine.xml
android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ImageProcessorFragment.java

Pretty straightforward update for this new preference.
Also fixed a couple of bugs:
- Wasn't using findcloudlet mode in the map activity.
- Wasn't using the carrier name for the ME calls within the CV activities.

EDGECLOUD-2956 Add support for setLimit for getAppInstances

---

android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/Cloudlet.java
android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/MainActivity.java
android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/MatchingEngineHelper.java
android/MobiledgeXSDKDemo/app/src/main/java/com/mobiledgex/sdkdemo/SettingsActivity.java
android/MobiledgeXSDKDemo/app/src/main/res/values/strings.xml
android/MobiledgeXSDKDemo/app/src/main/res/xml/pref_headers.xml

Garner's update for EDGECLOUD-3184 would have fixed the main problem, but I made this update to get a debug version of the app available immediately. It's simpler, so I'm keeping it.
There's also a fix for the Settings screen.

EDGECLOUD-3187 Fix performance mode cloudlet map

---

ComputerVisionServer/Makefile
ComputerVisionServer/moedx/facial_detection/tcp_server.py
FaceTrainingServer/facerec/trainer/views.py

Also minor logging and return value updates.

EDGECLOUD-2889 Makefile is now easier to change org name

---

unity/ComputerVision-UnityClient/Assets/Scripts/AppManager.cs
unity/ComputerVision-UnityClient/Assets/Scripts/DataContracts.cs
unity/ComputerVision-UnityClient/Assets/Scripts/NetworkManager.cs
unity/ComputerVision-UnityClient/Assets/Scripts/UIManager.cs

1. Licenses.
2. Different Texture for Object Detection & Face Recognition ( Green & Red Textures).
3. EnableInteraction() if Register&FindCloudlet ran without issues.
4. Object Detection (Show confidence level next to the object class)

CV-Unity Scripts Update

---

unity/PingPongGameExample/PingPongGame/Assets/Scripts/NetworkManager.cs

PingPong Completed Example uses Wifi

PingPong-UseWifiOnly

---

unity/ComputerVision-UnityClient/Assets/Scenes/ComputerVision.unity
unity/ComputerVision-UnityClient/Assets/Scripts/AppManager.cs
unity/ComputerVision-UnityClient/Assets/Scripts/NetworkManager.cs

Full process Latency(ms)  = network latency + server processing time + time to transfer the image data and receive back the results
Server Processing Time (ms)= server_processing_time from the server response
Distance to Cloudlet (miles) = Distance between cloudlet (from FindCloudlet Reply) and the User Location (Location Service) using Haversine formula

Latency Calculation

---

android/WorkshopCompleted/.idea/compiler.xml
android/WorkshopCompleted/.idea/gradle.xml
android/WorkshopCompleted/.idea/misc.xml
android/WorkshopCompleted/app/build.gradle
android/WorkshopCompleted/app/src/main/java/com/mobiledgex/workshopskeleton/MainActivity.java
android/WorkshopCompleted/build.gradle
android/WorkshopCompleted/gradle/wrapper/gradle-wrapper.properties
android/WorkshopSkeleton/.idea/compiler.xml
android/WorkshopSkeleton/.idea/gradle.xml
android/WorkshopSkeleton/.idea/misc.xml
android/WorkshopSkeleton/app/build.gradle
android/WorkshopSkeleton/build.gradle
android/WorkshopSkeleton/gradle/wrapper/gradle-wrapper.properties

- New SDK version
- Also allowed IDE-prompted Gradle updates.

Updating workshop apps for SDK version 2.4.0

---

ComputerVisionServer/requirements.txt

a breaking change in the newest version.

EDGECLOUD-4602 Specifying version of Twisted library to avoid

---

ComputerVisionServer/CUSTOM-WEIGHTS.md

If you click the 3-dot menu for CUSTOM-WEIGHTS.md, you can select "View File", you can see the Markdown formatted version,

EDGECLOUD-4680 Doc for deploying custom weights file

---

ComputerVisionServer/moedx/static/js/index.js

Same fixes as done for the edge-face-detection repo.

EDGECLOUD-4679 Don't stop on 500 error. Non-TLS WS fix.

---

android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ImageSender.java

EDGECLOUD-2553 Remove base64 encoding of image data

---

iOS/ARShooterExample/ARShooterGame/ARShooter/LoginViewController/LoginViewController.swift

Text-only change. Didn't even need to fix my broken iOS build environment to make this update.

EDGECLOUD-5197 Update orgName to MobiledgeX-Samples

---

android/MobiledgeXSDKDemo/CHANGELOG.md

Old version was only available internally at https://mobiledgex.atlassian.net/wiki/spaces/SWDEV/pages/152535041/Android+SDK+Demo+App+Release+Notes. This will be part of the open source repo.

EDGECLOUD-4525 Adding CHANGELOG.md to project

---

unity/ComputerVision-UnityClient/.gitignore
unity/ComputerVision-UnityClient/Assets/Scenes/ComputerVision.unity
unity/ComputerVision-UnityClient/Packages/manifest.json

1. Add Unity SDK to manifest.json.
2. Set EU DME as the default for CV.

Set EU as the default region for CV

---

android/EmptyMatchEngineMavenApp/app/build.gradle
android/EmptyMatchEngineMavenApp/app/src/main/java/com/mobiledgex/emptymatchengineapp/MainActivity.java

Mini.
3.0-rc1 strings.
Add EdgeEventsConfig comment text changes.

3.0-rc1 strings. Fix nits.

---

android/MobiledgeXSDKDemo/app/build.gradle
android/MobiledgeXSDKDemo/computervision/src/main/java/com/mobiledgex/computervision/ImageProcessorFragment.java
android/MobiledgeXSDKDemo/matchingenginehelper/src/main/java/com/mobiledgex/matchingenginehelper/EventLogViewer.java
android/MobiledgeXSDKDemo/matchingenginehelper/src/main/java/com/mobiledgex/matchingenginehelper/MatchingEngineHelper.java
android/MobiledgeXSDKDemo/matchingenginehelper/src/main/res/values/strings.xml

- Fix CV crash after location spoof.
- Save Log Event Viewer Auto Expand preference.
- Create new thread for postLocationUpdate so that it doesn't end up queued and delayed.

Fixes for issues seen during Jim's demo.

---

android/EmptyMatchEngineMavenApp/app/build.gradle
android/EmptyMatchEngineMavenApp/app/src/main/java/com/mobiledgex/emptymatchengineapp/MainActivity.java

Bump version depedency to 3.0 release.

Update Android EmptyMatchingEngineMavenApp to v3.0 SDK
